# .semaphore/production-deploy.yml
version: v1.0
name: Deploy website
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Deploy
    task:
      secrets:
        - name: jjbgf-secrets
      jobs:
        - name: Copy to Server
          commands:
            # - checkout
            - cache restore website-build
            - ls -l
            - lftp --help
            - cd dist/
            - lftp -c "open -u $FTP_USER,$FTP_PASSWORD ftp.jjbgf.de; set ssl:verify-certificate no; mirror -R ./ master/"
          # - name: Copy to S3
          #   commands:
          #     - checkout
          #     - cache restore website-build
          #     - ./scripts/deploy
